name: 'PIT Solutions '
favicon: null
layout_spectrum: 0.20264854817651212
typography_spectrum: 0.74514
title: A brain for your hardware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b92227'
    - '#231f20'
    - '#000000'
    - '#4d4d4d'
    - '#ff0000'
  brandStrength: 0.8264642751310021
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
